language: ruby
rvm:
- 2.4.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: gem install github-pages html-proofer
script: jekyll build && htmlproofer ./_site

# script: ls
# script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true # route your build to the container-based infrastructure for a faster build