# Site wide configuration

title:            "AWider.NET -- Committed to Expanding the OSS community for .NET"
sitename:         "A Wider .NET"
locale:           en_US
url:              http://AWider.NET
baseurl:          ""

# Github Metadata integration
repository: AWiderDotNet/AWiderDotNet.github.io

# Jekyll configuration
github: [metadata]
github_repo_url: http://github.com/AWiderDotNet/AWiderDotNet.github.io/
timezone: America/New_York
post-images: /images/post-images
permalink:   /:year/:month/:title/
markdown:    kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

social:
  - title: twitter
    url: https://twitter.com/AWiderDotNet
  - title: github
    url: https://github.com/AWiderDotNet
